project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "STAT 202"
  description: "Homepage for STAT 202"
  #site-url: "https://stat202_website.github.io/website/"
  site-url: "https://dsass1.github.io/stat202_async/"
  
  repo-url: https://github.com/dsass1/stat202_async
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  
  sidebar:
    -id: stat202-web
    background: "#BBB8B8"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: person-fill
        href: https://campuswire.com/c/G6C07549E
        text: "Campuswire"
      - icon: laptop
        href: https://northwestern.zoom.us/j/99863923813
        text: "Zoom"
    style: "docked"
    search: true
    contents:
        - href: index.qmd
          text: Today's agenda
        - href: course-week1.qmd
          text: Week 1
        # - href: course-project.qmd
        #   text: Final project
        # - href: course-anu.qmd
        #   text: Accessible NU
        - section: "Additional Resources"
          contents:
          - href: course-syllabus.qmd
            text: Syllabus
        #   - href: course-team.qmd
        #     text: Office hours
        #   - href: course-links.qmd
        #     text: Useful links
        #   - href: course-lectures.qmd
        #    text: Lecture videos
          - href: course-solutions.qmd
            text: Activity solutions
        #   - href: course-ec.qmd
        #     text: Extra Credit
          # - href: course-irl.qmd
          #   text: Stats and Data IRL
          

format:
  html:
    theme: [cosmo, style.scss]
    toc: true
    link-external-newwindow: true
    include-in-header: "style/fontawesome.html"

freeze: auto

editor: visual


