---
title: "Week 5 (July 15 - July 21)"
editor_options: 
  chunk_output_type: console
execute:
  
  message: false
  warning: false
  echo: false
from: markdown+emoji
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
#library(tidyverse)
library(gt)
library(gtExtras)
library(lubridate)
library(dplyr)
library(tidyr)
library(purrr)

agenda <- read.csv("documents/agenda_final.csv") 
```

::: slide-deck
**Reminders!**

-   Complete Week 4 first!
-   Make sure you review the [Activity Solutions](/course-solutions.html)
-   I suggest spacing out the lessons so you are working on 1 a day.
- Chapters 9 - 12 are hard! Make sure you attend office hours if you are struggling. Do NOT procrastinate! If you wait until the last day to start these you probably will not finish.
:::

::: tutorial
Complete [Course Survey 2](https://canvas.northwestern.edu/courses/192604/quizzes/209275)

(Don't skip this it's anonymous and worth points!)
:::


::: alert
Check out the  [Final Project Tab](/course-project.html)

  - you are free to begin working on the project whenever you would like
  - Final project is due 7/30 11:59pm
:::

::: slide-deck
**Lesson 15**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8a3fc6be-2903-40cd-89c0-b03b0110c274)
:::

::: slides
[Lecture slides 15 here](/slides/lec15.html)
:::

::: source
Read [Sections 9.2 - 9.3](https://nustat.github.io/intro-stat-data-sci/09-sampling-distributions.html)
:::

::: source
Complete: [Reading Check 15](https://amkuyper.shinyapps.io/15_sampling2/)
:::

::: source
Complete [Activity 15](https://posit.cloud/spaces/321338/content/5176493)
:::

::: homework
Submit [RC_15](https://canvas.northwestern.edu/courses/192604/assignments/1244683)

Submit [Activity 15](https://canvas.northwestern.edu/courses/192604/assignments/1244648)

**Due Friday 7/21 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 16**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d07dbd2c-e056-45af-b30e-b03b0110c237)
:::

::: slides
[Lecture slides 16 here](/slides/lec16.html)
:::

::: source
Read [Sections 9.4 - 9.7](https://nustat.github.io/intro-stat-data-sci/09-sampling-distributions.html)
:::

::: source
Complete: [Reading Check 16](https://amkuyper.shinyapps.io/16_sampling3/)
:::

::: source
Complete [Activity 16](https://posit.cloud/spaces/321338/content/5176494)
:::

::: homework
Submit [RC_16](https://canvas.northwestern.edu/courses/192604/assignments/1244684)

Submit [Activity 16](https://canvas.northwestern.edu/courses/192604/assignments/1244649)

**Due Friday 7/21 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 17**

::: video
Watch [lecture video part 1](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d17982f4-e45d-4db1-ab72-b03c00d99c19)
:::

::: slides
[Lecture slides 17 here](/slides/lec17.html)
:::

::: source
Read [Chapter 10](https://nustat.github.io/intro-stat-data-sci/10-confidence-intervals.html)
:::

::: source
Complete: [Reading Check 17](https://amkuyper.shinyapps.io/17_CI/)
:::

::: source
Start [Activity 17](https://posit.cloud/spaces/321338/content/5176495)

- Suggest completing Exercise 1
:::

::: video
Watch [lecture video part 2](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9e2170f9-e787-4c6a-a5f3-b03c00d99c43)
:::

::: slides
[Lecture slides 18 here](/slides/lec18.html)
:::

::: source
Finish [Activity 17](https://posit.cloud/spaces/321338/content/5176495)
:::

::: homework
Submit [RC_17](https://canvas.northwestern.edu/courses/192604/assignments/1244685)

Submit [Activity 17](https://canvas.northwestern.edu/courses/192604/assignments/1244650)

**Due Friday 7/21 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 18**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7216a1d2-ed47-46af-aab6-b03c00fc51ce)
:::

::: slides
[Lecture slides 19 here](/slides/lec19.html)
:::

::: source
Read [Chapter 11](https://nustat.github.io/intro-stat-data-sci/11-p-values.html)
:::

::: source
Complete: [Reading Check 18](https://amkuyper.shinyapps.io/18_pvalues/)
:::

::: source
Complete [Activity 18](https://posit.cloud/spaces/321338/content/5176496)
:::

::: homework
Submit [RC_18](https://canvas.northwestern.edu/courses/192604/assignments/1244686)

Submit [Activity 18](https://canvas.northwestern.edu/courses/192604/assignments/1244651)

**Due Sunday 7/23 11:59pm CT**
:::
:::

::: lab
Selected Exercise Guide for Activities 15 - 18. Suggest watching AFTER you have attempted the activity.

::: video
Watch [Activity 15 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=80722f10-0306-49db-93b3-b03d01113091)
:::

::: video
Watch [Activity 16 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4456df7b-cf35-4834-bbc6-b03d01113071)
:::

::: video
Watch [Activity 17 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=74f0674f-4753-4781-9114-b03d014c51c9)
:::

::: video
Watch [Activity 18 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=53569631-a392-4181-b701-b03d014c51a7)
:::
:::
