---
title: "Week 3 (July 01 - July 07)"
editor_options: 
  chunk_output_type: console
execute:
  
  message: false
  warning: false
  echo: false
from: markdown+emoji
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
#library(tidyverse)
library(gt)
library(gtExtras)
library(lubridate)
library(dplyr)
library(tidyr)
library(purrr)

agenda <- read.csv("documents/agenda_final.csv") 
```

::: slide-deck
**Reminders!**

- Complete Week 2 first!
-   Make sure you review the [Activity Solutions](/course-solutions.html)
-   I suggest spacing out the lessons so you are working on 1 a day.
:::


::: tutorial

Complete [Course Survey 1](https://canvas.northwestern.edu/courses/192604/quizzes/209278)

(Don't skip this it's anonymous and worth points!)
:::

::: slide-deck
**Lesson 8**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f04d629a-7a6d-458a-8429-b03100d16a0a)
:::

::: slides
[Lecture slides 08 here](/slides/lec08.html)
:::

::: source
Read [Sections 5.0 - 5.1](https://nustat.github.io/intro-stat-data-sci/05-regression.html)
:::

::: source
Complete: [Reading Check 08](https://amkuyper.shinyapps.io/08_regression1/)
:::

::: source
Complete [Activity 08](https://posit.cloud/spaces/321338/content/5176486)
:::

::: homework
Submit [RC_08](https://canvas.northwestern.edu/courses/192604/assignments/1244676)

Submit [Activity 08](https://canvas.northwestern.edu/courses/192604/assignments/1244641)

**Due Friday 7/07 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 9**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=598e9e41-2f2a-435e-8a0e-b03100d169d0)
:::

::: slides
[Lecture slides 09 here](/slides/lec09.html)
:::

::: source
Read [Sections 5.2 - 5.4](https://nustat.github.io/intro-stat-data-sci/05-regression.html)
:::

::: source
Complete: [Reading Check 09](https://amkuyper.shinyapps.io/09_regression2/)
:::

::: source
Complete [Activity 09](https://posit.cloud/spaces/321338/content/5176487)
:::

::: homework
Submit [RC_09](https://canvas.northwestern.edu/courses/192604/assignments/1244677)

Submit [Activity 09](https://canvas.northwestern.edu/courses/192604/assignments/1244642)

**Due Friday 7/07 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 10**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ccffb5e8-624d-458c-b4db-b03100d16978)
:::

::: slides
[Lecture slides 10 here](/slides/lec10.html)
:::

::: source
Read [Sections 6.0 - 6.1](https://nustat.github.io/intro-stat-data-sci/06-multiple-regression.html)
:::

::: source
Complete: [Reading Check 10](https://amkuyper.shinyapps.io/10_regression3/)
:::

::: source
Complete [Activity 10](https://posit.cloud/spaces/321338/content/5176488)
:::

::: homework
Submit [RC_10](https://canvas.northwestern.edu/courses/192604/assignments/1244678)

Submit [Activity 10](https://canvas.northwestern.edu/courses/192604/assignments/1244643)

**Due Friday 7/07 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 11**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d758dfc0-f25d-4ac2-bb87-b03100d16933)
:::

::: slides
[Lecture slides 11 here](/slides/lec11.html)
:::

::: source
Read [Sections 6.2 - 6.4](https://nustat.github.io/intro-stat-data-sci/06-multiple-regression.html)
:::

::: source
Complete: [Reading Check 11](https://amkuyper.shinyapps.io/11_regression4/)
:::

::: source
Complete [Activity 11](https://posit.cloud/spaces/321338/content/5176489)
:::

::: homework
Submit [RC_11](https://canvas.northwestern.edu/courses/192604/assignments/1244679)

Submit [Activity 11](https://canvas.northwestern.edu/courses/192604/assignments/1244644)

**Due Friday 7/07 11:59pm CT**
:::
:::

::: lab
Selected Exercise Guide for Activities 8 - 11. Do not watch until AFTER you have attempted the activity.

::: video
Watch [Activity 8 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=29ca7d52-42a6-4ab8-bfa4-b034012a783b)
:::

::: video
Watch [Activity 9 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ea29da12-12f4-4b18-ba3b-b034012a7814)
:::

::: video
Watch [Activity 10 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=04d986e4-d4b7-42a6-92ae-b03600f2437c)
:::

::: video
Watch [Activity 11 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=51336f4b-0883-4b75-abe5-b03601550ceb)
:::
:::
