---
title: "Week 6 (July 22 - July 30)"
editor_options: 
  chunk_output_type: console
execute:
  
  message: false
  warning: false
  echo: false
from: markdown+emoji
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
#library(tidyverse)
library(gt)
library(gtExtras)
library(lubridate)
library(dplyr)
library(tidyr)
library(purrr)

agenda <- read.csv("documents/agenda_final.csv") 
```

::: slide-deck
**Annoucements!**

-   Make sure you review the [Activity Solutions](/course-solutions.html)
-   I suggest spacing out the lessons so you are working on 1 a day.
-   Exam 3 is due by Friday July 28th 11:59pm CT; take whenever you are ready.
-   Final project is due by Sunday July 30th 11:59pm CT
:::

::: slide-deck
**Lesson 19**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=84c05231-7ae9-4648-864e-b03c00fc5201)
:::

::: slides
[Lecture slides 20 here](/slides/lec20.html)
:::

::: source
Read [Chapter 12](https://nustat.github.io/intro-stat-data-sci/12-hypothesis-tests.html)
:::

::: source
Complete: [Reading Check 19](https://amkuyper.shinyapps.io/19_hypothesis/)
:::

::: source
Complete [Activity 19](https://posit.cloud/spaces/321338/content/5176497)
:::

::: homework
Submit [RC_19](https://canvas.northwestern.edu/courses/192604/assignments/1244687)

Submit [Activity 19](https://canvas.northwestern.edu/courses/192604/assignments/1244652)

**Due Wednesday 7/26 11:59pm CT**
:::
:::

::: slide-deck
**Lesson 20**

::: video
Watch [lecture video](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=28624328-8479-4fdb-984d-b03c00fc528c)
:::

::: slides
[Lecture slides 21 here](/slides/lec21.html)
:::


::: source
Complete [Activity 20](https://posit.cloud/spaces/321338/content/5176498)
:::

::: homework
Submit [Activity 20](https://canvas.northwestern.edu/courses/192604/assignments/1244653)

**Due Wednesday 7/26 11:59pm CT**
:::
:::

::: lab
Selected Exercise Guide for Activities 19 - 20. Suggest watching AFTER you have attempted the activity.


::: video
Watch [Activity 19 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=47672cfa-cbc8-4796-b5fb-b04200f81068)
:::

::: video
Watch [Activity 20 solution guide](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=2c23c619-472d-443e-b9e9-b04200f8102c)
:::
:::


::: slide-deck
Take [Practice Exam 3](https://amkuyper.shinyapps.io/sample_exam3_v2/)

-   The actual exam will be self-timed (set a timer!) for 60 minutes.

::: video
Watch [Practice Exam 3 Solution](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8d240f58-ddc2-488c-9a23-b04300f2afd3)
:::
:::

::: exam
Exam 3 is due by Friday July 28th 11:59pm CT.

Important:

-   Set a timer for 60 minutes (or your ANU time).
-   **If you run out of time still finish and submit the problems you are working on - I will be the judge if it is excessive time.**
-   Don't spend too long on one question! Pace yourself. Students take these exams during the school year in 50 minutes - I am giving you 10 extra minutes.
-   Strongly suggest making a one page "cheat-sheet". While this exam is open note/open book - **if you do not understand the material you will NOT finish within the time limit - study**!.
-   Make sure you SUBMIT every Exercise and Question (not just run code you must click Submit). Unsubmitted exercises = 0
-   Check your submissions BEFORE locking the exam. Once you lock the exam no changes can be made.
-   Strongly suggest taking the practice exam prior.
-   Good luck!

::: video
[Exam directions](https://northwestern.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a3d44862-c110-432a-b538-b02f00e70d18) - same as Exam 1 but might be a good refresher.
:::

Take [Exam 3](https://posit.cloud/spaces/321338/content/5176507)

Submit [Exam 3](https://canvas.northwestern.edu/courses/192604/assignments/1244664)
:::


::: tutorial
Complete [Course Survey 3](https://canvas.northwestern.edu/courses/192604/quizzes/212405)

(Don't skip this it's anonymous and worth points!)
:::

::: slide-deck
Submit [Final Project](https://canvas.northwestern.edu/courses/192604/assignments/1244666)

- If you are in a group only 1 member must submit
- Look at your document before you submit! You do not want to turn in an html that has not been rendered after completing the qmd. I can't grade sections that I can't see.

:::
