---
title: "Repeated Sampling <br> 9.5 - 9.6"
institute: "Department of Statistics and Data Science <br> STAT 202"

logo: nu_logo.png
format: 
  revealjs:
    theme: [default, nu_theme.scss]
    chalkboard:
      theme: whiteboard
      toggleNotesButton: false
    menu:
        side: right
    code-line-numbers: false
    scrollable: true

execute:
  message: false
  warning: false
  echo: true
---

## The Reality

<br>

We are never going to take thousands of samples and construct a sampling distribution. The concept of random sampling is entirely theoretical and lays the foundations for the derivations of the standard errors in Table 9.6.

## Central Limit Theorem

::: incremental
-   A **sampling distribution** of a mean ($\bar{x})$ will get closer and closer to the normal curve as the number of repetitions increases. This is true no matter the shape of the original data!

-   The mean of your sampling distribution is the same as the population mean. $mean(\bar{x}) = \mu$.

-   The standard error of your sampling distribution is less than the spread of the population. $SE(\bar{x}) = \frac{\sigma}{\sqrt{n} }$

-   Statistical representation: $$\bar{x} \sim N\left(\mu_{\bar{x}} = \mu_x, SE(\bar{x})= \frac{\sigma_x}{\sqrt{n}}\right)$$
:::

## What makes a good sample?

::: incremental
-   representative of the population
-   picked at random (avoids bias)
-   big enough size to draw conclusions from ($n \geq 30$)
-   Exception: If the population is already normal, the results hold for samples of any size $n$
:::

. . .

**Requirement for CLT to hold true**

-   independent samples - includes less than 10% of the population (too big of a sample $n$ will create dependence between samples)
