---
title: "Hypothesis Testing <br> Chapter 12 <br> (Part 1)"
institute: "Department of Statistics and Data Science <br> STAT 202"

logo: nu_logo.png
format: 
  revealjs:
    theme: [default, nu_theme.scss]
    chalkboard:
      theme: whiteboard
      toggleNotesButton: false
    menu:
        side: right
    code-line-numbers: false
    scrollable: true

execute:
  message: false
  warning: false
  echo: true
---

## Example {.smaller}

Suppose Jill Thrillseeker is going sky diving. Jill will be inspecting the parachute before using it. No matter the inspection, we can never be 100% sure the parachute will work until we pull the rip cord to deploy it.

. . .

-   $H_0:$ the parachute is packed correctly (meaning it will work)

-   $H_A:$ the parachute is not packed correctly (meaning it will not work)

. . .

Describe the 4 possible scenarios and their consequences.

. . .

<!-- ## 4 Possible Scenarios -->

|                                   | Alternative $H_A$ is true | Null $H_0$ is true |
|-----------------------------------|---------------------------|--------------------|
| Reject the null hypothesis        | Scenario 1                | Scenario 2         |
| Do not reject the null hypothesis | Scenario 3                | Scenario 4         |

<!-- ## Scenario 1: Correct Decision -->

<!-- -   True Positive -->

<!-- -   **Decision**: Jill decides the parachute is NOT packed correctly -->

<!-- -   **Truth**: parachute was NOT packed correctly -->

<!-- -   **Result**: The parachute was NOT packed correctly and Jill decides to repack it. Jill's life is saved! -->

<!-- ## Scenario 2: Type I Error -->

<!-- -   False Positive -->

<!-- -   **Decision**: Jill decides the parachute is NOT packed correctly -->

<!-- -   **Truth**: parachute was packed correctly all along -->

<!-- -   **Result**: Jill wasted time and energy repacking the parachute -->

<!-- ## Scenario 3: Type II Error -->

<!-- -   False Negative -->

<!-- -   **Decision**: Jill decides the parachute is packed correctly -->

<!-- -   **Truth**: parachute was NOT packed correctly -->

<!-- -   **Result**: Jill jumps out with a bad parachute and probably dies -->

<!-- ## Scenario 4: Correct Decision -->

<!-- -   True Negative -->

<!-- -   **Decision**: Jill decides the parachute is packed correctly -->

<!-- -   **Truth**: parachute was packed correctly -->

<!-- -   **Result**: The parachute is packed correctly and opens, so Jill floats safely to the ground -->

## 4 Possible Scenarios Results

|                                   | Alternative $H_A$ is true | Null $H_0$ is true |
|-----------------------------------|---------------------------|--------------------|
| Reject the null hypothesis        | Correct Decision          | **Type I Error**   |
| Do not reject the null hypothesis | **Type II Error**         | Correct Decision   |

## Error

::: panel-tabset
## Type 1

-   Reject the null hypothesis when it is true
-   False Positive
-   Significance level
-   $\alpha$ = probability of a Type I error

## Type II error

-   Fail to reject the null hypothesis when it is false
-   False Negative
-   $\beta$ = probability of a Type II error

## Power

-   The probability of correctly rejecting the null hypothesis when it is false
-   Correct rejection decision
-   $\textbf{Power} = 1 - \beta$
:::
