on:
  push:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:
  schedule:
    # run every day at 1 AM central (6am UTC)
    - cron: '0 6 * * 1,3,5'

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
    
      - name: Install curl
        run: |-
          Rscript -e "install.packages(c('curl'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libssl-dev
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
        
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
#          folder: docs # The folder the action should deploy.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
          
#      - name: Deploy 🚀
#        if: github.event_name != 'pull_request'
#        uses: JamesIves/github-pages-deploy-action@4.1.7
#        with:
#          branch: gh-pages # The branch the action should deploy to.
#          folder: docs # The folder the action should deploy.

#      - name: Publish to GitHub Pages (and render)
#        uses: quarto-dev/quarto-actions/publish@v2
#        with:
#          target: gh-pages
          
